const Map<String, String> en = {
  "settings": "Settings",
  "general": "GENERAL",
  "notifications": "Notifications",
  "theme": "Theme",
  "dark_mode": "Dark Mode",
  "language": "Language",
  "about": "About",
  "privacy_policy": "Privacy Policy",
  "app": "APP",
  "view_policy": "View policy",
  "version": "Version",
  "pomodoro_timer": "Pomodoro Timer",
  "pomodoro": "Pomodoro",
  "break": "Break",
  "focus_time": "FOCUS TIME",
  "break_time": "BREAK TIME",
  "set_timer": "Set Timer",
  "minutes": "Minutes",
  "seconds": "Seconds",
  "cancel": "Cancel",
  "save": "Save",
  "session_finished": "Session Finished",
  "pomodoro_finished": "Pomodoro finished. Start break?",
  "break_finished": "Break finished. Start focus?",
  "stop_alarm": "Stop Alarm",
  "start_break": "Start Break",
  "start_focus": "Start Focus",
};
