const Map<String, String> vi = {
  "settings": "Cài đặt",
  "general": "CHUNG",
  "notifications": "Thông báo",
  "theme": "Giao diện",
  "dark_mode": "Chế độ tối",
  "language": "Ngôn ngữ",
  "about": "Giới thiệu",
  "privacy_policy": "Chính sách bảo mật",
  "app": "ỨNG DỤNG",
  "view_policy": "Xem chính sách",
  "version": "Phiên bản",
  "pomodoro_timer": "Bộ đếm Pomodoro",
  "pomodoro": "Tập trung",
  "break": "Nghỉ",
  "focus_time": "THỜI GIAN TẬP TRUNG",
  "break_time": "THỜI GIAN NGHỈ",
  "set_timer": "Đặt bộ đếm",
  "minutes": "Phút",
  "seconds": "Giây",
  "cancel": "Hủy",
  "save": "Lưu",
  "session_finished": "Phiên đã kết thúc",
  "pomodoro_finished":
      "Phiên tập trung đã kết thúc. Bắt đầu nghỉ ngơi?",
  "break_finished": "Phiên nghỉ đã kết thúc. Bắt đầu tập trung?",
  "stop_alarm": "Dừng Cảnh Báo",
  "start_break": "Bắt Đầu Nghỉ Ngơi",
  "start_focus": "Bắt Đầu Tập Trung",
  "student": "SINH VIÊN",
  "full_name": "Họ và tên",
  "student_id": "Mã số sinh viên",
  "instructor": "GIẢNG VIÊN",
  "instructor_1": "Giảng viên",
  "group_info": "Thông tin nhóm",
  "group_27": "Nhóm 27",
  "course": "Môn học",
  "mobile_device_programming": "Lập trình thiết bị di động",
  "timer": "Bộ đếm",
  "tasks": "Công việc",
  "info": "Thông tin",
  "title": "tiêu đề",
  "done": "hoàn thành",
  "search_tasks": "Tìm kiếm công việc...",
  "no_tasks": "Chưa có công việc nào",
  "add_task": "Thêm công việc",
  "task_name": "Tên công việc",
  "enter_task": "Nhập công việc...",
  "save_task": "Lưu công việc",
};
